{"uid":"7aa55d77c28e28c7","name":"修改收款单失败，金额为空","fullName":"test_case_fundsmanagement_receipt.TestCasereceipt#test_4_change_customer","historyId":"678cb310a1b4e7f5774b3bf480546f98","time":{"start":1673079435372,"stop":1673079454620,"duration":19248},"description":"基础设置-新增收款单用例","descriptionHtml":"<p>基础设置-新增收款单用例</p>\n","status":"failed","statusMessage":"pytest_assume.plugin.FailedAssumption: \n1 Failed Assumptions:\n\ntest_case_fundsmanagement_receipt.py:38: AssumptionFailure\n>>\tpytest.assume(self.lp == udata['message'])\nAssertionError:","statusTrace":"tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               1 Failed Assumptions:\nE               \nE               test_case_fundsmanagement_receipt.py:38: AssumptionFailure\nE               >>\tpytest.assume(self.lp == udata['message'])\nE               AssertionError:\n\nD:\\Pycharm\\Python\\venv\\lib\\site-packages\\six.py:718: FailedAssumption","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1673079240499,"stop":1673079240611,"duration":112},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"hasContent":false},{"name":"init_driver","time":{"start":1673079240611,"stop":1673079263655,"duration":23044},"status":"passed","steps":[],"attachments":[{"uid":"9c7fd1dfa17f0f98","name":"点击('xpath', '//*[@id=\"cancelAccountContainer\"]/div[1]/div/div[1]/div/div/button/i')选择企业后","source":"9c7fd1dfa17f0f98.png","type":"image/png","size":77631},{"uid":"faf0648fc3090edc","name":"点击('xpath', '//*[@id=\"cancelAccountContainer\"]/div[1]/div/div[1]/div/div/button/i')进入账套后","source":"faf0648fc3090edc.png","type":"image/png","size":87315},{"uid":"dc913c3534d11c93","name":"对('xpath', '//*[@id=\"cancelAccountContainer\"]/div[2]/div[1]/div[1]/ul/li[3]/button/span/span')打开进销存后","source":"dc913c3534d11c93.png","type":"image/png","size":87878}],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":3,"stepsCount":0,"hasContent":true},{"name":"Receipt","time":{"start":1673079263655,"stop":1673079272074,"duration":8419},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"hasContent":false}],"testStage":{"description":"基础设置-新增收款单用例","status":"failed","statusMessage":"pytest_assume.plugin.FailedAssumption: \n1 Failed Assumptions:\n\ntest_case_fundsmanagement_receipt.py:38: AssumptionFailure\n>>\tpytest.assume(self.lp == udata['message'])\nAssertionError:","statusTrace":"tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               1 Failed Assumptions:\nE               \nE               test_case_fundsmanagement_receipt.py:38: AssumptionFailure\nE               >>\tpytest.assume(self.lp == udata['message'])\nE               AssertionError:\n\nD:\\Pycharm\\Python\\venv\\lib\\site-packages\\six.py:718: FailedAssumption","steps":[],"attachments":[{"uid":"d697c15a8f75c89a","name":"点击末张","source":"d697c15a8f75c89a.png","type":"image/png","size":65286},{"uid":"5364bb08f135c6a2","name":"点击金额","source":"5364bb08f135c6a2.png","type":"image/png","size":64977},{"uid":"d134ec4a873c5c45","name":"点击金额","source":"d134ec4a873c5c45.png","type":"image/png","size":65445},{"uid":"eba088228138b854","name":"清空金额","source":"eba088228138b854.png","type":"image/png","size":65445},{"uid":"652bb1eb51aa2bbc","name":"点击自动核销","source":"652bb1eb51aa2bbc.png","type":"image/png","size":65050},{"uid":"d8fe99854158663c","name":"点击保存","source":"d8fe99854158663c.png","type":"image/png","size":67520},{"uid":"b0cba62809818f3f","name":"断言信息","source":"b0cba62809818f3f.txt","type":"text/plain","size":66},{"uid":"f7ee47318ca4fb77","name":"失败截图","source":"f7ee47318ca4fb77.png","type":"image/png","size":65816}],"parameters":[],"shouldDisplayMessage":true,"attachmentsCount":8,"stepsCount":0,"hasContent":true},"afterStages":[{"name":"init_driver::0","time":{"start":1673079470176,"stop":1673079474429,"duration":4253},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"hasContent":false}],"labels":[{"name":"epic","value":"资金管理"},{"name":"story","value":"修改收款单名称"},{"name":"feature","value":"收款单模块"},{"name":"tag","value":"@pytest.mark.usefixtures('Receipt')"},{"name":"suite","value":"test_case_fundsmanagement_receipt"},{"name":"subSuite","value":"TestCasereceipt"},{"name":"host","value":"DESKTOP-KEJFEBN"},{"name":"thread","value":"24804-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test_case_fundsmanagement_receipt"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"udata","value":"{'Name': '修改收款单数据02', 'legend': '修改收款单失败，金额为空', 'message': '收款金额不能小于本次核销金额'}"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":["@pytest.mark.usefixtures('Receipt')"]},"source":"7aa55d77c28e28c7.json","parameterValues":["{'Name': '修改收款单数据02', 'legend': '修改收款单失败，金额为空', 'message': '收款金额不能小于本次核销金额'}"]}